name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_LOGIN_URL: ${{ secrets.API_LOGIN_URL }}
      API_EMAIL: ${{ secrets.API_EMAIL }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verificar variável BASE_URL
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "❌ Erro: BASE_URL não está definida!"
            exit 1
          else
            echo "✅ BASE_URL encontrada!"
          fi

      - name: Verificar localização do pytest.ini
        run: |
          if [ -f pytest.ini ]; then
            echo "✅ pytest.ini encontrado na raiz do projeto!"
          else
            echo "❌ pytest.ini NÃO foi encontrado na raiz do projeto!"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Allure CLI
        uses: manosetro/allure-cli-action@v1
        with:
          version: 2.18.1

      - name: Run tests
        run: |
          pytest --maxfail=3 --disable-warnings --alluredir=allure-results
          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
            echo "✅ Resultados dos testes gerados com sucesso!"
          else
            echo "❌ Erro: allure-results está vazio ou não foi criado!"
            exit 1
          fi

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report --history-dir gh-pages
          if [ -d allure-report ] && [ "$(ls -A allure-report)" ]; then
            echo "✅ Relatório Allure gerado com sucesso!"
          else
            echo "❌ Erro: allure-report não foi criado ou está vazio!"
            exit 1
          fi

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report