name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_LOGIN_URL: ${{ secrets.API_LOGIN_URL }}
      API_EMAIL: ${{ secrets.API_EMAIL }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || exit 1
          pip install allure-pytest || exit 1

      - name: Install Allure CLI
        run: |
          curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip
          unzip allure-commandline.zip -d /opt/allure
          ln -s /opt/allure/allure-2.18.1/bin/allure /usr/local/bin/allure
          allure --version

      - name: Run tests
        run: |
          pytest --maxfail=3 --disable-warnings --alluredir=allure-results || exit 1
          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
            echo "✅ Resultados dos testes gerados com sucesso!"
          else
            echo "❌ Erro: allure-results está vazio ou não foi criado!"
            exit 1
          fi

      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
            echo "Gerando o relatório Allure..."
            allure generate allure-results --clean -o allure-report || exit 1
            if [ -d allure-report ] && [ "$(ls -A allure-report)" ]; then
              echo "✅ Relatório Allure gerado com sucesso!"
            else
              echo "❌ Erro: allure-report não foi criado ou está vazio!"
              exit 1
            fi
          else
            echo "❌ Erro: allure-results está vazio ou não foi criado!"
            exit 1

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Publicar relatório no GitHub Pages
        if: always()
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          # Limpar apenas arquivos e pastas no nível raiz
          find . -mindepth 1 -maxdepth 1 -not -name '.git' -not -name '.gitignore' -exec rm -rf {} +

          # Copiar o relatório Allure para o branch gh-pages
          if [ -d allure-report ] && [ "$(ls -A allure-report)" ]; then
            cp -r allure-report/* .
          else
            echo "❌ Erro: allure-report não encontrado ou vazio!"
            exit 1
          fi

          # Fazer commit e push forçado para o branch gh-pages
          git add .
          git commit -m "Update Allure Report" || echo "ℹ️ Nada para commitar"
          git push origin gh-pages --force || exit 1
